### ISSUE TITLE
project is wrongly named

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#13]
ok - belatedly realised the project is wrongly named - we need a consistent name moving forward from budgie-remix to ubuntu budgie.

suggest "budgie-welcome"

To-Do:
1. change the github project name (I'll do that)
2. change the debian branch control and changelog file
3. change the .desktop file
4. change anywhere that refers to the .desktop file

**Comment by niyasc** [comment]
**Done**

- [x] Project name has been changed
- [x] Updated `.desktop` file and all other references to `budge-welcome` https://github.com/budgie-remix/budgie-welcome/commit/682679d39fb4def58d1152aff51f03cfe7a507d6

-------------------
**TODO**
- [ ] Confused with `policy` file and that need to be updated
- [ ] Need to update `debian` branch

@fossfreedom  Can you take care of these two things?

**Comment by fossfreedom** [comment]
the policy file and repository installer is used in ubuntu-mate-welcome to enable you to run commands without needing to shell out to scripts.

Lets not worry about this for the first release - we can relook at this to remove the shell scripts a little later.
